### ISSUE TITLE
WebView import from react-native deprecated

### ISSUE THREAD

**Issue by Vaneste** [rynobax/react-native-plotly#13]
Hi and thanks for this great job!

Is it possible to update it to import WebView from react-native-webview (https://github.com/react-native-community/react-native-webview) as recommended by react-native team -  WebView will be soon removed from react-native package ?

- Please note that I tried to do that myself before asking but I don't know enough to get it working! Just a newbie here :D

Thanks!
Arnaud.

**Comment by mm-ns** [comment]
Bump! Have the same issue. @rynobax this must be broken for everyone... do you have a solution?

**Comment by rynobax** [comment]
I released a beta version `2.0.0-0` which uses `react-native-webview`.  I need to test it on an iOS device before doing an official release.

**Comment by mm-ns** [comment]
@rynobax great thanks! I'll check out that specific version and monitor for the official release :) Look forward! Thanks!

PS: Also if you can change the example that'd be great cause just putting in the new beta doesn't work right off the bat, at least on ios :) (tried with #15 )

**Comment by rynobax** [comment]
2.0.0 (and 3.0.0) has been released

**Comment by mm-ns** [comment]
@rynobax I still get this:

![image](https://user-images.githubusercontent.com/26540637/68070336-5290e180-fd6d-11e9-9f69-1eb19877f95c.png)

could you perhaps upload a demo project or let us know how to modify the one you have? I did a search through the code and I can't seem to find anywhere where WebView is still referenced from react-native..

**Comment by Vaneste** [comment]
> 
> 
> 2.0.0 (and 3.0.0) has been released

Thanks a lot ! I'll test this soon.
